HEADERS = -I.\
		-I include

SOURCES = source/ej2.cpp 

Ej2 : 
	g++ -std=c++17 -Wall -Wextra -Wpedantic -pthread $(HEADERS) -g example/main2.cpp $(SOURCES) -o ej2
	./ej2

clean : 
	rm -f ej2 
	rm -f *.dSYM/ 

